#!/usr/bin/env bash
# Install Nginx and configure

# install nginx
apt-get update
apt-get -y install nginx

# adjust the firewall
ufw allow 'Nginx HTTP'

if [ -d "/etc/nginx/html" ]
then
  echo "Directory /etc/nginx/html already exists. Skipping..."
else
  mkdir /etc/nginx/html
fi

echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
        listen 80 default_server;
        listen [::]:80 default_server;
	server_name _;

	location / {
		add_header X-Served-By $HOSTNAME;
		root       /etc/nginx/html;
		index      index.html index.htm;
	}
}" > /etc/nginx/sites-available/default

# restart nginx
service nginx restart
