#!/usr/bin/env bash
# Setup load balancer

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y  ppa:vbernat/haproxy-2.0

# install haproxy
sudo apt-get update -y
sudo apt-get install -y haproxy=2.0.\*

# enable the HAProxy init script
echo "ENABLED=1" >> /etc/default/haproxy

# backup original config
cp -a /etc/haproxy/haproxy.cfg{,.orig}

{
	echo -e "\nfrontend http"
	echo -e "\tbind *:80"
	echo -e "\toption forwardfor"
	echo -e "\tdefault_backend nginx_webservers"
	echo -e "\nbackend nginx_webservers"
	echo -e "\tbalance roundrobin"
	echo -e "\tserver 65257-web-01\t54.237.78.109 check port 80"
	echo -e "\tserver 65257-web-02\t54.210.182.37 check port 80"
} >> /etc/haproxy/haproxy.cfg

# restart haproxy
service haproxy restart
