#!/usr/bin/env bash
# Script fixes a server with bad nginx sites-enabled configuration
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
