#!/usr/bin/env bash
# Script displays numbers from 1 to 100.
#   Displays FizzBuzz when the number is a multiple of 3 and 5
#   Displays Fizz when the number is multiple of 3
#   Displays Buzz when the number is a multiple of 5
#   Otherwise, displays the number

i=1

while [ $i -le 100 ]
do
	if (( $i % 15 == 0 ))
	then
		echo "FizzBuzz"
	elif (( $i % 5 == 0 ))
	then
		echo "Buzz"
	elif (( $i % 3 == 0 ))
	then
		echo "Fizz"
	else
		echo "$i"
	fi
	(( i++ ))
done
