#!/usr/bin/env bash
# echo 'bad luck' on 4th iteration and 'good luck' on 8th iteration
# else ech 'Best School'

i=1

while [ $i -lt 11 ]
do
  if [ $i -eq 4 ]
  then
    echo "bad luck"
  elif [ $i -eq 8 ]
  then
    echo "good luck"
  else
    echo "Best School"
  fi
  (( i++ ))
done
